### ISSUE TITLE
asynccp with sockets example

### ISSUE THREAD

**Issue by LMBooth** [WarriorOfWire/CircuitPython_async#13]
Hi, great library! 

I'm attempting to handle a socket connection  and pass that connection between two async functions to pose as a reader and writer.  my reader (`GetCommand`) is receiving data but my writer (`DoTask`) doesn't seem to be calling. Is there a problem with me sharing sockets across async functions?

Here's an example of what i'm trying in case there's any glaringly obvious errors or protocols - CircuitPython code on ESP32-S2-WROVER-I:
``` python
import wifi
import asynccp
import socketpool
import time

bufSize = 40
buf = bytearray(bufSize)
mv_buf = memoryview(buf)
count = 0

async def DoTask(conn): 
    # originally had custom functions for spi to attached device, 
    # would poll for new data before incrementing through buffer
    global count
    mv_buf[count] = count
    count += 1
    time.sleep(0.01)
    if count == 40:  
        conn.send(mv_buf)
        count = 0
        print("sent buffer")

async def GetCommand(conn):
    buffer = bytearray(256) 
    size = conn.recv_into(buffer, 256)
    print(buffer[:size])
 
async def loop(conn):
    await GetCommand(conn)
    await DoTask(conn)
    

def StartWiFiServer():
    ssid = "esp32-s2"
    password = "password123"
    wifi.radio.enabled = True
    wifi.radio.start_ap(ssid, password)  
   
if __name__ == "__main__":   
    print("Running main.py")
    StartWiFiServer()
    pool = socketpool.SocketPool(wifi.radio) 
    s = pool.socket(pool.AF_INET, pool.SOCK_STREAM)
    s.setblocking(1)
    HOST = "192.168.4.1"
    s.bind((HOST, 99)) 
    s.listen(1)
    while True: 
        conn, addr = s.accept()
        with conn: 
            print("Connected by", addr)
            asynccp.add_task(loop(conn)) 
            asynccp.run()
```

PC code:

``` python
import socket

HOST = "192.168.4.1" # The server's hostname or IP address
PORT = 99  # The port used by the server

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.settimeout(None)

    print("Connecting")
    s.connect((HOST, PORT))

    array = [1,2,3,5,4]  
    s.send(bytes(array))    
    
    #s.rea
    res = s.recv(40, socket.MSG_WAITALL)
    print(res)
```

**Comment by LMBooth** [comment]
As a thought, would it be possible to do something like micropythons uasyncio.start_server to create readers and writers for tcp connections more easily? Or is this functionality already implemented in something i'm overlooking?

**Comment by LMBooth** [comment]
I've had another go implementing something similar with schedule but run in to some form of error (see traceback below) after a couple buffers are succesfully transmitted.

```
Traceback (most recent call last):
  File "code.py", line 51, in <module>
  File "asynccp/loop.py", line 268, in run
  File "asynccp/loop.py", line 282, in _step
  File "asynccp/loop.py", line 303, in _run_task
  File "asynccp/loop.py", line 101, in _run_at_fixed_rate
  File "code.py", line 22, in GetCommand
OSError: [Errno 11] EAGAIN
```


CircuitPython code on ESP32-S2-WROVER-I:
``` python
import wifi
import asynccp
import socketpool
import time 

bufSize = 40
buf = bytearray(bufSize)
mv_buf = memoryview(buf)
count = 0

async def DoTask(conn):
    global count, mv_buf
    mv_buf[count] = count
    count += 1
    if count == 40:  
        conn.send(mv_buf)
        count = 0
        print("sent buffer")

async def GetCommand(conn):
    buffer = bytearray(256) 
    size = conn.recv_into(buffer, 256)
    print(buffer[:size])
 
async def loop(conn):
    await DoTask(conn)
    await GetCommand(conn)

def StartWiFiServer():
    ssid = "esp32-s2"
    password = "password123"
    wifi.radio.enabled = True
    wifi.radio.start_ap(ssid, password)  
   
if __name__ == "__main__":   
    print("Running main.py")
    StartWiFiServer()
    pool = socketpool.SocketPool(wifi.radio) 
    s = pool.socket(pool.AF_INET, pool.SOCK_STREAM)
    s.setblocking(1)
    HOST = "192.168.4.1"
    s.bind((HOST, 99)) 
    s.listen(1)
    while True: 
        conn, addr = s.accept()
        with conn: 
            print("Connected by", addr)
            #asynccp.add_task(loop(conn)) 
            asynccp.schedule(1, GetCommand, conn)
            asynccp.schedule(100, DoTask, conn)
            asynccp.run()
```

PC code:
``` python
import socket

HOST = "192.168.4.1" # The server's hostname or IP address
PORT = 99  # The port used by the server

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.settimeout(None)

    print("Connecting")
    s.connect((HOST, PORT))

    
    array = [1,2,3,5,4]  
    s.send(bytes(array))  
    while True:
    
        res = s.recv(40, socket.MSG_WAITALL)
        if len(res)==40:
            print(res)
```

**Comment by kvc0** [comment]
Your traceback indicates a socket error in `size = conn.recv_into(buffer, 256)`. I’m unfamiliar with Circuitpython socket code, but it looks like it’s timing out or closing the connection or something like that. Does the circuitpython socket library expect you to park the application on `accept()` so it can do internal bookkeeping?

**Comment by LMBooth** [comment]
When you say park it on accept what do you mean?

My decision for the socket handling came from [the TCP server socket example here.](https://github.com/anecdata/Socket/blob/main/examples/tcp_server_CircuitPython_NATIVE.py).

**Comment by kvc0** [comment]
your pc code sends only 1 message. If you’re crashing after 2 buffers are transmitted then probably your recv_into is crashing when 0 bytes are available.
Again, I’m not deep on circuitpython socket code. This isn’t an asynccp issue. :-) Maybe you would get more help on the circuitpython discord?

fyi I don’t think you’re getting a lot of value out of asynccp with the code you’ve got here. Maybe you’re planning to do more interesting stuff in your connection handlers that needs to wait or something though. Good luck!
